name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build with dotnet
      run: dotnet build
    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"      
    - name: reportgenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@0.0.1
      with:
        reports: '*Test/TestResults/*/coverage.cobertura.xml'
        targetdir: 'CoverageReports'
        reporttypes: 'HtmlInline;Cobertura'
    - name: Upload artifact
		reports: '*Test/TestResults/*/coverage.cobertura.xml'
		targetdir: 'CoverageReports'
		reporttypes: 'HtmlInline;Cobertura'
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: CoverageReports
        # Directory containing files to upload
        path: CoverageReports
